// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	product "ecommerce/features/product"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// Add provides a mock function with given fields: file, token, newProduct
func (_m *ProductService) Add(file multipart.FileHeader, token interface{}, newProduct product.Core) (product.Core, error) {
	ret := _m.Called(file, token, newProduct)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(multipart.FileHeader, interface{}, product.Core) product.Core); ok {
		r0 = rf(file, token, newProduct)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(multipart.FileHeader, interface{}, product.Core) error); ok {
		r1 = rf(file, token, newProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, contentID
func (_m *ProductService) Delete(token interface{}, contentID uint) error {
	ret := _m.Called(token, contentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, contentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductDetail provides a mock function with given fields: productID
func (_m *ProductService) ProductDetail(productID uint) (product.Core, error) {
	ret := _m.Called(productID)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(uint) product.Core); ok {
		r0 = rf(productID)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductList provides a mock function with given fields:
func (_m *ProductService) ProductList() ([]product.Core, error) {
	ret := _m.Called()

	var r0 []product.Core
	if rf, ok := ret.Get(0).(func() []product.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: file, token, contentID, updatedProduct
func (_m *ProductService) Update(file multipart.FileHeader, token interface{}, contentID uint, updatedProduct product.Core) (product.Core, error) {
	ret := _m.Called(file, token, contentID, updatedProduct)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(multipart.FileHeader, interface{}, uint, product.Core) product.Core); ok {
		r0 = rf(file, token, contentID, updatedProduct)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(multipart.FileHeader, interface{}, uint, product.Core) error); ok {
		r1 = rf(file, token, contentID, updatedProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductService interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductService(t mockConstructorTestingTNewProductService) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
